# Generated by Django 2.2.6 on 2024-02-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('mobile_number', models.IntegerField()),
                ('address', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('course', models.CharField(max_length=255, null=True)),
                ('specialization', models.CharField(max_length=255, null=True)),
                ('course_type', models.CharField(max_length=100, null=True)),
                ('college', models.CharField(max_length=255, null=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('year_of_passing', models.IntegerField(null=True)),
                ('skills', models.CharField(max_length=255, null=True)),
                ('summary', models.TextField()),
                ('experience_level', models.CharField(max_length=100, null=True)),
                ('designation', models.CharField(max_length=255)),
                ('responsibilities', models.TextField()),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255, null=True)),
                ('worked_from', models.DateField(null=True)),
                ('to', models.DateField(null=True)),
                ('about_company', models.TextField()),
                ('website', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
